### PR TITLE
Fix callstack and errorType of logError, fixes #78

### LINKED ISSUE #78: Log more detailed info about unhandled exceptions

### PR DESCRIPTION
**Pull request by StephenWeatherford**

### CODE REVIEW

File: src/AzureRMTools.ts [hunk 1]
```diff
@@ -430,6 +430,7 @@ export class AzureRMTools {
 
         this.logOnError(() => {
             const deploymentTemplate = this.getDeploymentTemplate(document);
+            throw new Error("hi");
```
Comment (PrashanthCorp) [inline src/AzureRMTools.ts]: Did you mean to leave the `hi` in?

Comment (StephenWeatherford) [reply src/AzureRMTools.ts]: whoops
