### PR TITLE
Better handle async errors

### LINKED ISSUE #38: Revamp telemetry

### LINKED ISSUE #115: Provide means for feedback straight from extension

### LINKED ISSUE #166: No problems have been detected when opening the file errors.jsonc
**OS:** Windows/MacOS
**Node.js:** 10.15.0
**Regression:** Previous release 0.4.2
**Build Version:** [20190214.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3213&view=results)

**Repro Steps:**
1. Open the file errors.jsonc in VS Code.
2. Check the "PROBLEMS"

**Expect:**
Detect and show problems. 
image

**Actual:**
No problems have be detected.
image

**More Info**: The content of error.jsonc file as below:

{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "domainNamePrefix": {
      "type": "string",
      "metadata": {
        "description": "The public DNS name label for the service.  The pattern will follow: <domainNamePrefix>.<region>.cloudapp.azure.com"
      }
    },
    "vmssName": {
      "type": "string",
      "metadata": {
        "description": "String used as a base for naming resources (9 characters or less). A hash is prepended to this string for some resources, and resource-specific information is appended."
      },
      "maxLength": 9
    },
    "automationAccountName": {
      "type": "string",
      "defaultValue": "myAutomationAccount",
      "metadata": {
        "description": "The name of the Automation account to use.  Check the SKU and tags to make sure they match the existing account."
      }
    },
    "automationRegionId": {
      "type": "string",
      "defaultValue": "East US 2",
      "allowedValues": [
        "Japan East",
        "East US 2",
        "West Europe",
        "Southeast Asia",
        "South Central US",
        "Central India"
      ],
      "metadata": {
        "description": "The region the Automation account is located in."
      }
    },
    "configurationName": {
      "type": "string",
      "defaultValue": "MyService",
      "metadata": {
        "description": "The name of the DSC Configuration. The name must match the name in the URI."
      }
    },
    "jobid": {
      "type": "string",
      "metadata": {
        "description": "The job id to compile the configuration"
      }
    }
  },
  "variables": {
    "saCount": 5,
    "namingInfix": "[toLower(parameters('vmssName'))]",
    "newStorageAccountSuffix": "[concat(variables('namingInfix'), 'sa')]",
    "uniqueStringArray": [
      "[concat(uniqueString(concat(resourceGroup().id, deployment().name, variables('newStorageAccountSuffix'), '0')))]",
      "[concat(uniqueString(concat(resourceGroup().id, deployment().name, variables('newStorageAccountSuffix'), '1')))]",
      "[concat(uniqueString(concat(resourceGroup().id, deployment().name, variables('newStorageAccountSuffix'), '2')))]",
      "[concat(uniqueString(concat(resourceGroup().id, deployment().name, variables('newStorageAccountSuffix'), '3')))]",
      "[concat(uniqueString(concat(resourceGroup().id, deployment().name, variables('newStorageAccountSuffix'), '4')))]"
    ],
    "publicIPAddressName": "[concat(variables('namingInfix'), 'pip')]",
    "publicIPAddressID": "[resourceId('Microsoft.Network/publicIPAddresses/',variables('publicIPAddressName'))]",
    "osType": {
      "publisher": "MicrosoftWindowsServer",
      "offer": "WindowsServer",
      "sku": "[parameters('windowsOSVersion')]",
      "version": "latest"
    },
    "automationPricingTier": "Free"
  },
  "resources": [
    {
      "type": "Microsoft.Automation/automationAccounts",
      "name": "[parameters('automationAccountName')]",
      "apiVersion": "2015-10-31",
      "location": "[parameters('automationRegionId')]",
      "dependsOn": [],
      "tags": {},
      "properties": {
        "sku": {
          "name": "[variables('automationPricingTier')]"
        }
      },
      "resources": [
        {
          "name": "[parameters('jobid')]",
          "type": "compilationjobs",
          "apiVersion": "2015-10-31",
          "location": "parameters('automationRegionId')]",
          "tags": {},
          "dependsOn": [
            "[concat('Microsoft.Automation/automationAccounts/', parameters('automationAccountName'))]",
            "[concat('Microsoft.Automation/automationAccounts/', parameters('automationAccountName'),'/Configurations/', parameters('configurationName'))]"
          ],
          "properties": {
            "configuration": {
              "name": "[parameters('configurationName')]"
            }
          }
        }
      ]
    },
    {
      "type": "Microsoft.Storage/storageAccounts",
      "name": "[concat(variables('uniqueStringArray')[copyindex(0,1)], variables('newStorageAccountSuffix'))]",
      "location": "[resourceGroup().location]",
      "apiVersion": "2015-06-15",
      "copy": {
        "name": "storageLoop",
        "count": "[variables('sacount')]"
      },
      "properties": {
        "accountType": "[variables('storageAccountType')]"
      }
    }
  ],
  "outputs": {
    "fqdn": {
      "value": "[reference(variables('publicIPAddressID'),'2017-04-01', 'Full').dnsSettings.fqdn]",
      "type": "string"
    },
    "ipaddress": {
      "value": "[reference(variables('publicIPAddressID'),'2017-04-01').ipAddress]",
      "type": "string"
    }
  }
}

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #166, fixes #115, fixes #38 

The fix for #166 is correcting the path in getLocalAssetUri (removing a ".." to adjust for webpack change).  This error was getting ignored, so the rest of the PR is:
1) Simplifying AzureRMAssets.ts (don't need everything to be calculated on demand) and making sure that errors get carried through
2) Rewriting error handling in AzureRMTools.ts to use callWithTelemetryAndErrorHandling.

### CODE REVIEW

File: src/AzureRMTools.ts [hunk 1]
```diff
@@ -91,38 +89,35 @@ export class AzureRMTools {
...
+        }
     }
 
     public dispose(): void {
-        this.logOnError(() => {
-            if (this._deploymentTemplateFileSubscriptions) {
-                this._deploymentTemplateFileSubscriptions.dispose();
+        const me = this;
+        callWithTelemetryAndErrorHandlingSync('dispose', function (this: IActionContext) {
+            this.properties.isActivationEvent = 'true';
```
Comment (EricJizbaMSFT) [inline src/AzureRMTools.ts]: should this suppressErrorDisplay? Might be weird if an error flashes up as you're closing VS Code

File: src/AzureRMTools.ts [hunk 2]
```diff
@@ -652,34 +627,47 @@ export class AzureRMTools {
...
-                        const referenceRange: vscode.Range = this.getVSCodeRangeFromSpan(deploymentTemplate, referenceSpan);
+                        const referenceRange: vscode.Range = me.getVSCodeRangeFromSpan(deploymentTemplate, referenceSpan);
                         result.replace(documentUri, referenceRange, newName);
                     }
                 } else {
-                    vscode.window.showInformationMessage("You can only rename parameters and variables.");
+                    const message = 'You can only rename parameters and variables.';
+                    vscode.window.showInformationMessage(message);
+                    this.suppressErrorDisplay = true;
+                    throw new Error(message);
```
Comment (EricJizbaMSFT) [inline src/AzureRMTools.ts]: Seems like you could remove:
```
vscode.window.showInformationMessage(message);
this.suppressErrorDisplay = true;
```

And let shared logic show this error
