### PR TITLE
952 Allow unlinking from params when template missing

### LINKED ISSUE #952: Unable to remove file reference from parameter file to template file if template file is deleted
Does this occur consistently? yes
Repro steps:

1. Create a template file
2. Create a template parameters file
3. Link the two using the extension
4. Delete the linked template file (preserving the parameter file)

It would be a great if when reporting this error an option was provided to remove the link.
Pressing the "Template File" to normally provide a template file just reproduces this error.

Action: azurerm-vscode-tools.openTemplateFile
Error type: Error
Error Message: cannot open file:///<path>/azureDeploy.json. Detail: Unable to read file 'path\azureDeploy.json' (Error: Unable to resolve non-existing file 'path\azureDeploy.json')

Version: 0.12.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6239:388
```

</details>

### LINKED ISSUE #1011: no such file or directory when template file missing
Repro steps:
1. Create a template and associated parameter file
2. Delete template file
3. Restart vscode and open param file

Action: reportDeploymentParametersErrors
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '/Users/stephenweatherford/repos/template-examples/child-resources/one.json'

Version: 0.13.0-alpha
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code - Insiders
Product Version: 1.50.0-insider
Language: en

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Depends on PR https://github.com/microsoft/vscode-azurearmtools/pull/1006

Fixes #952 
Fixes #1011 

Before:
image
After:
image

### CODE REVIEW

File: src/AzureRMTools.ts [hunk 1]
```diff
@@ -709,7 +709,16 @@ export class AzureRMTools {
         return await callWithTelemetryAndErrorHandling('reportDeploymentParametersErrors', async (actionContext: IActionContext): Promise<IErrorsAndWarnings> => {
             actionContext.telemetry.suppressIfSuccessful = true;
 
-            const template = await this.getOrReadAssociatedTemplate(textDocument.uri, Cancellation.cantCancel);
+            const templateUri: vscode.Uri | undefined = this._mapping.getTemplateFile(deploymentParameters.documentUri);
```
Comment (StephenWeatherford) [inline src/AzureRMTools.ts:712]: this fixes https://github.com/microsoft/vscode-azurearmtools/issues/1011
