### PR TITLE
Fix null span in some parse scenarios

### LINKED ISSUE #193: Random notifications with "documentColumnIndex cannot be greater than the line's maximum index"
Repro steps:
Really hard to tell what causes this specific issue as it seems fairly random.

I think it might happen when autocomplete suggestions are triggered. I use a smaller vscode window where it only takes half of my screen. My only guess is that perhaps there are some situations where the autocompletion menu might not have enough space to render?!

Although this notification happens fairly often, I have not been able to determine the exact steps that will reproduce it 100% of the time.

Action: provideCompletionItems
Error type: ERR_ASSERTION
Error Message: documentColumnIndex (27) cannot be greater than the line's maximum index (26)

Version: 0.5.0
OS: Arch linux
VS Code Version: 1.32.2

<details>
<summary>Call Stack</summary>

```
Function.fromDocumentLineAndColumnIndexes (dist/extension.bundle.js:127:96193)
DeploymentTemplate.getContextFromDocumentLineAndColumnIndexes (dist/extension.bundle.js:127:92640)
Object.<anonymous> (dist/extension.bundle.js:127:125835)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:127:117380)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:127:117157)
Object.<anonymous> (dist/extension.bundle.js:127:125744)
Object.<anonymous> (dist/extension.bundle.js:1:182883)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:1:181258)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:1:181035)
Object.module.exports.t.callWithTelemetryAndErrorHandling (dist/extension.bundle.js:1:182800)
AzureRMTools.<anonymous> (dist/extension.bundle.js:127:125667)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:127:117380)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:127:117157)
AzureRMTools.onProvideCompletionItems (dist/extension.bundle.js:127:125562)
Object.provideCompletionItems (dist/extension.bundle.js:127:121876)
define.provideCompletionItems.a.asPromise (extensionHostProcess.js:569:293)
t.asPromise.Promise (extensionHostProcess.js:48:58)
new Promise (<anonymous>)
Object.t.asPromise (extensionHostProcess.js:48:32)
O.provideCompletionItems (extensionHostProcess.js:569:264)
define.$provideCompletionItems._withAdapter.e (extensionHostProcess.js:582:811)
$._withAdapter (extensionHostProcess.js:575:502)
$provideCompletionItems (extensionHostProcess.js:582:789)
h._doInvokeHandler (extensionHostProcess.js:593:118)
h._invokeHandler (extensionHostProcess.js:592:777)
h._receiveRequest (extensionHostProcess.js:591:383)
h._receiveOneMessage (extensionHostProcess.js:590:279)
define.constructor._protocol.onMessage.e (extensionHostProcess.js:588:565)
u.fire (extensionHostProcess.js:43:254)
e (extensionHostProcess.js:39:64)
u.fire (extensionHostProcess.js:43:254)
s (extensionHostProcess.js:168:754)
Socket.define.constructor._socketDataListener.e (extensionHostProcess.js:168:960)
Socket.emit (events.js:182:13)
addChunk (_stream_readable.js:279:12)
readableAddChunk (_stream_readable.js:264:11)
Socket.Readable.push (_stream_readable.js:219:10)
Pipe.onread (net.js:636:20)
```

</details>

### LINKED ISSUE #221: Cannot read property span of null
let propertySpan: language.Span = null;
    let propertyName: StringValue = null;
    let foundColon: boolean = false;
    while (tokenizer.current) {
        objectSpan = objectSpan.union(tokenizer.current.span);

        if (tokenizer.current.type === TokenType.RightCurlyBracket) {
            next(tokenizer, tokens);
            break;
        } else if (propertyName === null) {
            if (tokenizer.current.type === TokenType.QuotedString) {
                propertySpan = tokenizer.current.span;
                propertyName = new StringValue(propertySpan, utilities.unquote(tokenizer.current.toString()));
                next(tokenizer, tokens);
            } else {
                next(tokenizer, tokens);
            }
        } else if (!foundColon) {
            propertySpan = propertySpan.union(tokenizer.current.span);
            if (tokenizer.current.type === TokenType.Colon) {
                foundColon = true;
                next(tokenizer, tokens);
            } else {
                propertyName = null;
            }
        } else {
            const propertyValue: Value = parseValue(tokenizer, tokens);
            propertySpan = propertySpan.union(propertyValue.span);

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #193, fixes #221 

Parsing is throwing, so the deployment template doesn't get updated from the current text, so the line/column info given to us by vscode can be invalid against our out-of-date stored document text.

### CODE REVIEW

File: src/JSON.ts [hunk 1]
```diff
@@ -1067,8 +1067,10 @@ function parseObject(tokenizer: Tokenizer, tokens: Token[]): ObjectValue {
...
         } else {
             const propertyValue: Value = parseValue(tokenizer, tokens);
-            propertySpan = propertySpan.union(propertyValue.span);
-            objectSpan = objectSpan.union(propertyValue.span);
+            if (propertyValue) {
+                propertySpan = propertySpan.union(propertyValue.span);
+                objectSpan = objectSpan.union(propertyValue.span);
+            }
 
             properties.push(new Property(propertySpan, propertyName, propertyValue));
```
Comment (EricJizbaMSFT) [inline src/JSON.ts]: Should this line also be inside `if (propertyValue) {`?

File: test/DeploymentTemplate.test.ts [hunk 2]
```diff
@@ -949,3 +950,101 @@ suite("ReferenceInVariableDefinitionJSONVisitor", () => {
...
+                "type": "string",
+                "value": "[parameters('adminUsername')]"
+            }
+        }
+    }
+    `;
+
+    test("https://github.com/Microsoft/vscode-azurearmtools/issues/193", () => {
+        let modifiedTemplate = template.replace('"type": "string"', '"type": string');
+        new DeploymentTemplate(modifiedTemplate, "id");
```
Comment (EricJizbaMSFT) [inline test/DeploymentTemplate.test.ts]: Any particular reason the other tests do `await dt.errors;` but this one doesn't?

Comment (StephenWeatherford) [reply test/DeploymentTemplate.test.ts]: Not really, the bug occurs during new DeploymentTemplate, I'll add it here, though.

File: src/JSON.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/JSON.ts]: No, we still create the property entry, it just doesn't have a property value token. Someday I'll have to strict-null this code, that will not be fun. :-(
