### PR TITLE
Always validate file if langid=ARM

### LINKED ISSUE #284: Expression diagnostics don't show up if the schema is wrong but the user switches manually to ARM Language Server
Functionality should be enabled based only on whether langid=arm-deployment (though we can automatically switch to that langid if the schema matches).

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #284

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
Ping

File: src/AzureRMTools.ts [hunk 1]
```diff
@@ -120,72 +120,56 @@ export class AzureRMTools {
...
-                    // If the documentUri is not in our dictionary of deployment templates, then we
-                    // know that this document was just opened (as opposed to changed/updated).
-                    let stopwatch: Stopwatch;
-                    const documentUri: string = document.uri.toString();
-                    if (!this._deploymentTemplates[documentUri]) {
-                        stopwatch = new Stopwatch();
-                        stopwatch.start();
-                    }
+            const stopwatch = new Stopwatch();
+            stopwatch.start();
```
Comment (PrashanthCorp) [inline src/AzureRMTools.ts]: Does this need to be accompanied by a stop?

File: src/AzureRMTools.ts [hunk 2]
```diff
@@ -120,72 +120,56 @@ export class AzureRMTools {
...
-                                    varsCount: deploymentTemplate.variableDefinitions.length,
-                                    namespacesCount: deploymentTemplate.namespaceDefinitions.length
-                                });
-
-                            this.logFunctionCounts(deploymentTemplate);
+                    if (isNewlyOpened) {
+                        // A deployment template has been opened (as opposed to having been tabbed to)
+
+                        // Make sure the language ID is set to ARM deployment template
+                        if (document.languageId !== armDeploymentLanguageId) {
```
Comment (PrashanthCorp) [inline src/AzureRMTools.ts]: What are the other possible values it can hold? I can see it having JSON. 
I'm wondering if modifying this might affect another extension that's also looking into this file.

File: src/AzureRMTools.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/AzureRMTools.ts]: No, it's just a thin wrapper on Date.now(), but thanks for asking.

File: src/AzureRMTools.ts (hunk 2 above)
Comment (StephenWeatherford) [reply src/AzureRMTools.ts]: We've notified the extensions we're aware of that might be affected. Ultimately the user has control of this, and can turn it off our automatic behavior with a setting.  Again, good question.

This was the solution suggested by vscode guys.
