### PR TITLE
Fix object disposed issue

### LINKED ISSUE #173: An error dialog pops up after closing one changed .json file
**Version:** 1.32.0-insider (user setup)
**Node.js**: 10.2.0
**OS:** All
**Extension Version**: [20190223.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3530)

**Steps to reproduce:**
1. Open one .json file from VS Code.
2. Change the contents of the opened file -> Try to close the opened tab.
3. Click 'Save' or 'Don't Save' on the popped confirmation dialog -> Check the result.

**Expect Experiment:**
No error occurs.

**Actual Experiment**:
Pop up an error dialog with the below message.
image

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #173 

The issue was that _diagnosticsCollection was disposed by disposing _deploymentTemplateFileSubscriptions, but was not set to null, so was still being accessed.

### CODE REVIEW

File: src/AzureRMTools.ts [hunk 1]
```diff
@@ -418,8 +433,7 @@ export class AzureRMTools {
             // Code editor. The events will be registered again when the next
             // deployment template is opened.
             if (Object.keys(this._deploymentTemplates).length === 0 && this._deploymentTemplateFileSubscriptions) {
```
Comment (EricJizbaMSFT) [inline src/AzureRMTools.ts]: nit: Since you're checking `this._deploymentTemplateFileSubscriptions` inside `unhookDeploymentFileEvents`, I would prefer to remove that check here

Comment (StephenWeatherford) [reply src/AzureRMTools.ts]: I'll consider for later.
