### PR TITLE
Linked template templateLink object does not create a new scope

### LINKED ISSUE #792: Regression from 0.10.0: top-level parameters not recognized in nested template properties
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "linkedTemplatesLocation": {
            "type": "string"
        }
    },
    "variables": {
        "firstTemplate": "../linkedTemplate1.json",
        "secondTemplate": "linkedTemplate2.json"
    },
    "resources": [
        // hello
        {
            "name": "nestedDeployment2",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2017-05-10",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[concat(parameters('linkedTemplatesLocation'), '/', variables('secondTemplate'))]",
                    "contentVersion": "1.0.0.0"
                },
                "parameters": {
                    "linked2param1": {
                        "value": "abc"
                    }
                }
            }
        },
        {
            "name": "nestedDeployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2017-05-10",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[concat(parameters('linkedTemplatesLocation'), '/', variables('firstTemplate'))]"
                },
                "parameters": {
                    "linked1param1": {
                        "value": "my value" // (error)
                    }
                }
            }
        }
    ],
    "outputs": {
    },
    "functions": [
    ]
}
```

EXPECTED (0.10.0): no errors
ACTUAL: Multiple errors, including:
Undefined variable reference: 'secondTemplate'

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #792

### CODE REVIEW

File: src/templateScopes.ts [hunk 1]
```diff
@@ -287,6 +287,7 @@ export class NestedTemplateOuterScope extends TemplateScope {
 
 export class LinkedTemplate extends TemplateScope {
     public constructor(
+        public readonly parentScope: TemplateScope,
```
Comment (alexgav) [inline src/templateScopes.ts:290]: >public [](start = 8, length = 6)

Nit: should this be public?

Comment (StephenWeatherford) [reply src/templateScopes.ts:290]: probably not
